# Use official Node.js 22 image
FROM node:22

WORKDIR /workdir

RUN apt-get update && apt-get install -y \
    curl \
    nano \
    git \
    ca-certificates \
    xz-utils \
    && rm -rf /var/lib/apt/lists/*

# Initialize npm project
RUN npm init -y

# Install brace-expansion
RUN npm install @intlify/message-resolver@9.1.10

CMD ["/bin/bash"]